version: "3.4"

services:
  mysql-users-microservice:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'ShiftDB'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: ShiftMicro*1234
      MYSQL_ROOT_PASSWORD: ShiftMicro*1234
    ports:
      - "3313:3306"
    volumes:
      - mysql_shift_caf_data:/var/lib/mysql

volumes:
  mysql_shift_caf_data:
    driver: local

networks:
  default:
    driver: bridge