server:
  port: 9091

spring:
  application:
    name: AUTH-MICROSERVICE
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://autorack.proxy.rlwy.net:27967/AuthenticationDB?createDatabaseIfNotExist=true
    username: root
    password: mVGfssOpJTXkgAInNhCSCvQYxJCjzbdw

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT-ID}
            client-secret: ${CLIENT-SECRET}
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
jwt:
  secret: Z0xkM0NkVllGd1N0dXZHRzY5MFBBQUlOUmhMRE1vOUhlSjhZNTdhdTZIRzJIQTFJdFhndA==

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: https://eureka-051n.onrender.com/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

admin-paths:
  paths:
    - uri: "/user/save"
      method: "POST"

    - uri: "/user/all"
      method: "GET"

    - uri: "/caf/all"
      method: "GET"

    - uri: "/caf/question/all"
      method: "GET"

    - uri: "/caf/change-coordinator"
      method: "POST"

    - uri: "/user/departments"
      method: "GET"

    - uri: "/user/programs"
      method: "GET"

    - uri: "/shift/allDayAssignments/{1}[1-9]+[0-9]*"
      method: "GET"

    - uri: "/shift/saveShift"
      method: "POST"

    - uri: "/shift/editShift"
      method: "PUT"

    - uri: "/shift/deleteShift"
      method: "PUT"

    - uri: "/shift/reserve/create-shift-instances/{1}[1-9]+[0-9]*"
      method: "POST"

    - uri: "/shift/shift-instances/finishShift/{1}[1-9]+[0-9]*"
      method: "POST"

    - uri: "/shift/shift-instances/actShift/{1}[1-9]+[0-9]*"
      method: "POST"

    - uri: "/auth/user/all"
      method: "GET"

wellbeing-director-paths:
  paths:
    - uri: "/user/all"
      method: "GET"

    - uri: "/user/departments"
      method: "GET"

    - uri: "/user/programs"
      method: "GET"

    - uri: "/user/{1}[1-9]+[0-9]*"
      method: "GET"

    - uri: "/user/save"
      method: "POST"

    - uri: "/user/departments"
      method: "GET"

    - uri: "/user/programs"
      method: "GET"

    - uri: "/caf/inscription/all/[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*@[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*[.][a-zA-Z]{2,5}"
      method: "GET"

    - uri: "/shift/allDayAssignments/{1}[1-9]+[0-9]*"
      method: "GET"

    - uri: "/shift/saveShift"
      method: "POST"

    - uri: "/shift/editShift"
      method: "PUT"

    - uri: "/shift/deleteShift"
      method: "PUT"

    - uri: "/shift/reserve/create-shift-instances/{1}[1-9]+[0-9]*"
      method: "POST"

    - uri: "/shift/shift-instances/finishShift/{1}[1-9]+[0-9]*"
      method: "POST"

    - uri: "/shift/shift-instances/actShift/{1}[1-9]+[0-9]*"
      method: "POST"

    - uri: "/auth/user/all"
      method: "GET"

caf-coordinator-paths:
  paths:
    - uri: "/user/{1}[1-9]+[0-9]*"
      method: "GET"

    - uri: "/caf/inscription/all/[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*@[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*[.][a-zA-Z]{2,5}"
      method: "GET"

    - uri: "/shift/reserve/create-shift-instances/{1}[1-9]+[0-9]*"
      method: "POST"

    - uri: "/shift/allDayAssignments/{1}[1-9]+[0-9]*"
      method: "GET"

    - uri: "/shift/saveShift"
      method: "POST"

    - uri: "/shift/editShift"
      method: "PUT"

    - uri: "/shift/deleteShift"
      method: "PUT"

    - uri: "/shift/reserve/create-shift-instances/{1}[1-9]+[0-9]*"
      method: "POST"

    - uri: "/shift/reserve/registry-attended-reserve"
      method: "POST"

    - uri: "/shift/shift-instances/finishShift/{1}[1-9]+[0-9]*"
      method: "POST"

    - uri: "/shift/shift-instances/actShift/{1}[1-9]+[0-9]*"
      method: "POST"

    - uri: "/auth/user/all"
      method: "GET"

user-paths:
  paths:
    - uri: "/user/{1}[1-9]+[0-9]*"
      method: "GET"

    - uri: "/caf/question/all"
      method: "GET"

    - uri: "/caf/all"
      method: "GET"

    - uri: "/caf/inscription/inscribe-user/[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*@[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*[.][a-zA-Z]{2,5}"
      method: "POST"

    - uri: "/user/save"
      method: "POST"

    - uri: "/caf/inscription/all/[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*@[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*[.][a-zA-Z]{2,5}"
      method: "GET"

    - uri: "/user/departments"
      method: "GET"

    - uri: "/user/programs"
      method: "GET"

    - uri: "/caf/files/upload/{1}[1-9]+[0-9]*"
      method: "POST"

    - uri: "/user/isUserOldMayor/[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*@[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*[.][a-zA-Z]{2,5}"
      method: "GET"

    - uri: "/shift/reserve/reserve-shift-user"
      method: "POST"

    - uri: "/shift/reserve/shift-instances-caf/{1}[1-9]+[0-9]*"
      method: "GET"

    - uri: "/shift/reserve/allReservationForUser/{1}[1-9]+[0-9]*"
      method: "GET"

    - uri: "/shift/reserve/cancelReservationForUser/{1}[1-9]+[0-9]*"
      method: "POST"

    - uri: "/shift/reserve/all-reservations-by-shift-instance/{1}[1-9]+[0-9]*"
      method: "GET"

sportsman-paths:
  paths:
    - uri: "/user/{1}[1-9]+[0-9]*"
      method: "GET"

    - uri: "/caf/question/all"
      method: "GET"

    - uri: "/user/save"
      method: "POST"

    - uri: "/user/departments"
      method: "GET"

    - uri: "/user/programs"
      method: "GET"

    - uri: "/shift/reserve/reserve-shift-user"
      method: "POST"

    - uri: "/shift/reserve/shift-instances-caf/{1}[1-9]+[0-9]*"
      method: "GET"

    - uri: "/shift/reserve/allReservationForUser/{1}[1-9]+[0-9]*"
      method: "GET"

    - uri: "/shift/reserve/cancelReservationForUser/{1}[1-9]+[0-9]*"
      method: "POST"