INSERT INTO UsersDB.faculty (faculty_name) VALUES 
('Ciencias agropecuarias'),
('Ciencias'),
('Ciencias de la educación'),
('Ciencias económicas y administrativas'),
('Ciencias de la salud'),
('Derecho'),
('Ingeniería'),
('Estudios a distancia'),
('Chiquinquirá'),
('Duitama'),
('Sogamoso'),
('Aguazul');

-- Ciencias agropecuarias
INSERT INTO UsersDB.program (program_name, faculty_id) VALUES 
('Ingeniería Agronómica', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias agropecuarias')),
('Medicina Veterinaria y Zootecnia ', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias agropecuarias'));

-- Ciencias
INSERT INTO UsersDB.program (program_name, faculty_id) VALUES 
('Biología', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias')),
('Química', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias')),
('Matemáticas', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias')),
('Física', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias'));

-- Ciencias de la educación
INSERT INTO UsersDB.program (program_name, faculty_id) VALUES 
('Licenciatura Ciencias Naturales y Educación Ambiental', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias de la educación')),
('Licenciatura Ciencias Sociales', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias de la educación')),
('Licenciatura Educación Física, Recreación y Deportes', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias de la educación')),
('Licenciatura Educación Infanti', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias de la educación')),
('Licenciatura Filosofía', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias de la educación')),
('Licenciatura en Literatura y Lengua Castellana', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias de la educación')),
('Licenciatura Lenguas Modernas, énfasis en Inglés', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias de la educación')),
('Licenciatura en Informática', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias de la educación')),
('Licenciatura Lenguas Extranjeras', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias de la educación')),
('Licenciatura Matemáticas', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias de la educación')),
('Licenciatura Música', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias de la educación')),
('Licenciatura Psicopedagogía, énfasis Asesoría Educación', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias de la educación'));

-- Ciencias económicas y administrativas
INSERT INTO UsersDB.program (program_name, faculty_id) VALUES 
('Economía', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias económicas y administrativas')),
('Administración de Empresas', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias económicas y administrativas')),
('Contaduría Pública', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias económicas y administrativas')),
('Finanzas y Comercio Internacional', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias económicas y administrativas'));

-- Ciencias de la salud
INSERT INTO UsersDB.program (program_name, faculty_id) VALUES 
('Medicina', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias de la salud')),
('Enfermería', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias de la salud')),
('Psicología', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ciencias de la salud'));

-- Derecho
INSERT INTO UsersDB.program (program_name, faculty_id) VALUES 
('Derecho', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Derecho'));

-- Ingeniería
INSERT INTO UsersDB.program (program_name, faculty_id) VALUES 
('Ingeniería Civil', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ingeniería')),
('Ingeniería Electrónica', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ingeniería')),
('Ingeniería de Sistemas y Computación', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ingeniería')),
('Ingeniería Metalúrgica', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ingeniería')),
('Ingeniería Electrónica', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ingeniería')),
('Ingeniería Electrónica', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ingeniería')),
('Ingeniería en Transportes y Vías', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ingeniería')),
('Ingeniería Ambiental', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ingeniería')),
('Arquitectura', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Ingeniería'));

-- Estudios a distancia
INSERT INTO UsersDB.program (program_name, faculty_id) VALUES 
('Administración Pública', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Estudios a distancia'));

-- Chiquinquirá
INSERT INTO UsersDB.program (program_name, faculty_id) VALUES 
('Licenciatura en Educación Básica con Énfasis en Humanidades e Idiomas', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Chiquinquirá')),
('Administración de Empresas', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Chiquinquirá')),
('Contaduría Pública', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Chiquinquirá')),
('Licenciatura Educación Física, Recreación y Deportes', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Chiquinquirá'));

-- Duitama
INSERT INTO UsersDB.program (program_name, faculty_id) VALUES 
('Licenciatura en Tecnología', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Duitama')),
('Administración de Empresas Agropecuarias', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Duitama')),
('Administración Industrial', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Duitama')),
('Administración Turística y Hotelera', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Duitama')),
('Diseño Industrial', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Duitama')),
('Ingeniería Electromecánica', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Duitama')),
('Licenciatura Matemáticas', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Duitama'));

-- Sogamoso
INSERT INTO UsersDB.program (program_name, faculty_id) VALUES 
('Ingeniería de Minas', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Sogamoso')),
('Ingeniería Geológica', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Sogamoso')),
('Administración de Empresas', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Sogamoso')),
('Contaduría Pública', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Sogamoso')),
('Ingeniería Electrónica', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Sogamoso')),
('Ingeniería de Sistemas y Computación', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Sogamoso')),
('Ingeniería Industrial', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Sogamoso'));

-- Aguazul
INSERT INTO UsersDB.program (program_name, faculty_id) VALUES 
('Derecho', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Aguazul')),
('Administración de Empresas Turística', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Aguazul')),
('Licenciatura Lenguas Modernas', (SELECT id FROM UsersDB.faculty WHERE faculty_name = 'Aguazul'));

-- Departments
INSERT INTO UsersDB.department (name)
VALUES
	('ANTIOQUIA'),
	('ATLÁNTICO'),
	('BOGOTÁ, D.C.'),
	('BOLÍVAR'),
	('BOYACÁ'),
	('CALDAS'),
	('CAQUETÁ'),
	('CAUCA'),
	('CESAR'),
	('CÓRDOBA'),
	('CUNDINAMARCA'),
	('CHOCÓ'),
	('HUILA'),
	('LA GUAJIRA'),
	('MAGDALENA'),
	('META'),
	('NARIÑO'),
	('NORTE DE SANTANDER'),
	('QUINDIO'),
	('RISARALDA'),
	('SANTANDER'),
	('SUCRE'),
	('TOLIMA'),
	('VALLE DEL CAUCA'),
	('ARAUCA'),
	('CASANARE'),
	('PUTUMAYO'),
	('ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA'),
	('AMAZONAS'),
	('GUAINÍA'),
	('GUAVIARE'),
	('VAUPÉS'),
	('VICHADA');

-- Boyaca cities
INSERT INTO UsersDB.city (name, department_id)
VALUES 
('Tununguá', 5),
('Motavita', 5),
('Ciénega', 5),
('Tunja', 5),
('Almeida', 5),
('Aquitania', 5),
('Arcabuco', 5),
('Berbeo', 5),
('Betéitiva', 5),
('Boavita', 5),
('Boyacá', 5),
('Briceño', 5),
('Buena Vista', 5),
('Busbanzá', 5),
('Caldas', 5),
('Campohermoso', 5),
('Cerinza', 5),
('Chinavita', 5),
('Chiquinquirá', 5),
('Chiscas', 5),
('Chita', 5),
('Chitaraque', 5),
('Chivatá', 5),
('Cómbita', 5),
('Coper', 5),
('Corrales', 5),
('Covarachía', 5),
('Cubará', 5),
('Cucaita', 5),
('Cuítiva', 5),
('Chíquiza', 5),
('Chivor', 5),
('Duitama', 5),
('El Cocuy', 5),
('El Espino', 5),
('Firavitoba', 5),
('Floresta', 5),
('Gachantivá', 5),
('Gameza', 5),
('Garagoa', 5),
('Guacamayas', 5),
('Guateque', 5),
('Guayatá', 5),
('Güicán', 5),
('Iza', 5),
('Jenesano', 5),
('Jericó', 5),
('Labranzagrande', 5),
('La Capilla', 5),
('La Victoria', 5),
('Macanal', 5),
('Maripí', 5),
('Miraflores', 5),
('Mongua', 5),
('Monguí', 5),
('Moniquirá', 5),
('Muzo', 5),
('Nobsa', 5),
('Nuevo Colón', 5),
('Oicatá', 5),
('Otanche', 5),
('Pachavita', 5),
('Páez', 5),
('Paipa', 5),
('Pajarito', 5),
('Panqueba', 5),
('Pauna', 5),
('Paya', 5),
('Pesca', 5),
('Pisba', 5),
('Puerto Boyacá', 5),
('Quípama', 5),
('Ramiriquí', 5),
('Ráquira', 5),
('Rondón', 5),
('Saboyá', 5),
('Sáchica', 5),
('Samacá', 5),
('San Eduardo', 5),
('San Mateo', 5),
('Santana', 5),
('Santa María', 5),
('Santa Sofía', 5),
('Sativanorte', 5),
('Sativasur', 5),
('Siachoque', 5),
('Soatá', 5),
('Socotá', 5),
('Socha', 5),
('Sogamoso', 5),
('Somondoco', 5),
('Sora', 5),
('Sotaquirá', 5),
('Soracá', 5),
('Susacón', 5),
('Sutamarchán', 5),
('Sutatenza', 5),
('Tasco', 5),
('Tenza', 5),
('Tibaná', 5),
('Tinjacá', 5),
('Tipacoque', 5),
('Toca', 5),
('Tópaga', 5),
('Tota', 5),
('Turmequé', 5),
('Tutazá', 5),
('Umbita', 5),
('Ventaquemada', 5),
('Viracachá', 5),
('Zetaquira', 5),
('Togüí', 5),
('Villa de Leyva', 5),
('Paz de Río', 5),
('Santa Rosa de Viterbo', 5),
('San Pablo de Borbur', 5),
('San Luis de Gaceno', 5),
('San José de Pare', 5),
('San Miguel de Sema', 5),
('Tuta', 5),
('Tibasosa', 5),
('La Uvita', 5),
('Belén', 5);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Medellín', 1),
('Abejorral', 1),
('Abriaquí', 1),
('Alejandría', 1),
('Amagá', 1),
('Amalfi', 1),
('Andes', 1),
('Angelópolis', 1),
('Angostura', 1),
('Anorí', 1),
('Anza', 1),
('Apartadó', 1),
('Arboletes', 1),
('Argelia', 1),
('Armenia', 1),
('Barbosa', 1),
('Bello', 1),
('Betania', 1),
('Betulia', 1),
('Ciudad Bolívar', 1),
('Briceño', 1),
('Buriticá', 1),
('Cáceres', 1),
('Caicedo', 1),
('Caldas', 1),
('Campamento', 1),
('Cañasgordas', 1),
('Caracolí', 1),
('Caramanta', 1),
('Carepa', 1),
('Carolina', 1),
('Caucasia', 1),
('Chigorodó', 1),
('Cisneros', 1),
('Cocorná', 1),
('Concepción', 1),
('Concordia', 1),
('Copacabana', 1),
('Dabeiba', 1),
('Don Matías', 1),
('Ebéjico', 1),
('El Bagre', 1),
('Entrerrios', 1),
('Envigado', 1),
('Fredonia', 1),
('Giraldo', 1),
('Girardota', 1),
('Gómez Plata', 1),
('Guadalupe', 1),
('Guarne', 1),
('Guatapé', 1),
('Heliconia', 1),
('Hispania', 1),
('Itagui', 1),
('Ituango', 1),
('Belmira', 1),
('Jericó', 1),
('La Ceja', 1),
('La Estrella', 1),
('La Pintada', 1),
('La Unión', 1),
('Liborina', 1),
('Maceo', 1),
('Marinilla', 1),
('Montebello', 1),
('Murindó', 1),
('Mutatá', 1),
('Nariño', 1),
('Necoclí', 1),
('Nechí', 1),
('Olaya', 1),
('Peñol', 1),
('Peque', 1),
('Pueblorrico', 1),
('Puerto Berrío', 1),
('Puerto Nare', 1),
('Puerto Triunfo', 1),
('Remedios', 1),
('Retiro', 1),
('Rionegro', 1),
('Sabanalarga', 1),
('Sabaneta', 1),
('Salgar', 1),
('San Francisco', 1),
('San Jerónimo', 1),
('San Luis', 1),
('San Pedro', 1),
('San Rafael', 1),
('San Roque', 1),
('San Vicente', 1),
('Santa Bárbara', 1),
('Santo Domingo', 1),
('El Santuario', 1),
('Segovia', 1),
('Sopetrán', 1),
('Támesis', 1),
('Tarazá', 1),
('Tarso', 1),
('Titiribí', 1),
('Toledo', 1),
('Turbo', 1),
('Uramita', 1),
('Urrao', 1),
('Valdivia', 1),
('Valparaíso', 1),
('Vegachí', 1),
('Venecia', 1),
('Yalí', 1),
('Yarumal', 1),
('Yolombó', 1),
('Yondó', 1),
('Zaragoza', 1),
('San Pedro de Uraba', 1),
('Santafé de Antioquia', 1),
('Santa Rosa de Osos', 1),
('San Andrés de Cuerquía', 1),
('Vigía del Fuerte', 1),
('San José de La Montaña', 1),
('San Juan de Urabá', 1),
('El Carmen de Viboral', 1),
('San Carlos', 1),
('Frontino', 1),
('Granada', 1),
('Jardín', 1),
('Sonsón', 1);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Yopal', 26),
('Aguazul', 26),
('Chámeza', 26),
('Hato Corozal', 26),
('La Salina', 26),
('Monterrey', 26),
('Pore', 26),
('Recetor', 26),
('Sabanalarga', 26),
('Sácama', 26),
('Tauramena', 26),
('Trinidad', 26),
('Villanueva', 26),
('San Luis de Gaceno', 26),
('Paz de Ariporo', 26),
('Nunchía', 26),
('Maní', 26),
('Támara', 26),
('Orocué', 26);


INSERT INTO UsersDB.city (name, department_id)
VALUES
('Manizales', 6),
('Aguadas', 6),
('Anserma', 6),
('Aranzazu', 6),
('Belalcázar', 6),
('Chinchiná', 6),
('Filadelfia', 6),
('La Dorada', 6),
('La Merced', 6),
('Manzanares', 6),
('Marmato', 6),
('Marulanda', 6),
('Neira', 6),
('Norcasia', 6),
('Pácora', 6),
('Palestina', 6),
('Pensilvania', 6),
('Riosucio', 6),
('Risaralda', 6),
('Salamina', 6),
('Samaná', 6),
('San José', 6),
('Supía', 6),
('Victoria', 6),
('Villamaría', 6),
('Viterbo', 6),
('Marquetalia', 6);


INSERT INTO UsersDB.city (name, department_id)
VALUES
('Anapoima', 11),
('Arbeláez', 11),
('Beltrán', 11),
('Bituima', 11),
('Bojacá', 11),
('Cabrera', 11),
('Cachipay', 11),
('Cajicá', 11),
('Caparrapí', 11),
('Caqueza', 11),
('Chaguaní', 11),
('Chipaque', 11),
('Choachí', 11),
('Chocontá', 11),
('Cogua', 11),
('Cota', 11),
('Cucunubá', 11),
('El Colegio', 11),
('El Rosal', 11),
('Fomeque', 11),
('Fosca', 11),
('Funza', 11),
('Fúquene', 11),
('Gachala', 11),
('Gachancipá', 11),
('Gachetá', 11),
('Girardot', 11),
('Granada', 11),
('Guachetá', 11),
('Guaduas', 11),
('Guasca', 11),
('Guataquí', 11),
('Guatavita', 11),
('Guayabetal', 11),
('Gutiérrez', 11),
('Jerusalén', 11),
('Junín', 11),
('La Calera', 11),
('La Mesa', 11),
('La Palma', 11),
('La Peña', 11),
('La Vega', 11),
('Lenguazaque', 11),
('Macheta', 11),
('Madrid', 11),
('Manta', 11),
('Medina', 11),
('Mosquera', 11),
('Nariño', 11),
('Nemocón', 11),
('Nilo', 11),
('Nimaima', 11),
('Nocaima', 11),
('Venecia', 11),
('Pacho', 11),
('Paime', 11),
('Pandi', 11),
('Paratebueno', 11),
('Pasca', 11),
('Puerto Salgar', 11),
('Pulí', 11),
('Quebradanegra', 11),
('Quetame', 11),
('Quipile', 11),
('Apulo', 11),
('Ricaurte', 11),
('San Bernardo', 11),
('San Cayetano', 11),
('San Francisco', 11),
('Sesquilé', 11),
('Sibaté', 11),
('Silvania', 11),
('Simijaca', 11),
('Soacha', 11),
('Subachoque', 11),
('Suesca', 11),
('Supatá', 11),
('Susa', 11),
('Sutatausa', 11),
('Tabio', 11),
('Tausa', 11),
('Tena', 11),
('Tenjo', 11),
('Tibacuy', 11),
('Tibirita', 11),
('Tocaima', 11),
('Tocancipá', 11),
('Topaipí', 11),
('Ubalá', 11),
('Ubaque', 11),
('Une', 11),
('Útica', 11),
('Vianí', 11),
('Villagómez', 11),
('Villapinzón', 11),
('Villeta', 11),
('Viotá', 11),
('Zipacón', 11),
('San Juan de Río Seco', 11),
('Villa de San Diego de Ubate', 11),
('Guayabal de Siquima', 11),
('San Antonio del Tequendama', 11),
('Agua de Dios', 11),
('Carmen de Carupa', 11),
('Vergara', 11),
('Albán', 11),
('Anolaima', 11),
('Chía', 11),
('El Peñón', 11),
('Sopó', 11),
('Gama', 11),
('Sasaima', 11),
('Yacopí', 11),
('Fusagasugá', 11),
('Zipaquirá', 11),
('Facatativá', 11);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Bogotá D.C.', 3);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Arauquita', 25),
('Cravo Norte', 25),
('Fortul', 25),
('Puerto Rondón', 25),
('Saravena', 25),
('Tame', 25),
('Arauca', 25);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Popayán', 8),
('Almaguer', 8),
('Argelia', 8),
('Balboa', 8),
('Bolívar', 8),
('Buenos Aires', 8),
('Cajibío', 8),
('Caldono', 8),
('Caloto', 8),
('Corinto', 8),
('El Tambo', 8),
('Florencia', 8),
('Guachené', 8),
('Guapi', 8),
('Inzá', 8),
('Jambaló', 8),
('La Sierra', 8),
('La Vega', 8),
('López', 8),
('Mercaderes', 8),
('Miranda', 8),
('Morales', 8),
('Padilla', 8),
('Patía', 8),
('Piamonte', 8),
('Piendamó', 8),
('Puerto Tejada', 8),
('Puracé', 8),
('Rosas', 8),
('Santa Rosa', 8),
('Silvia', 8),
('Sotara', 8),
('Suárez', 8),
('Sucre', 8),
('Timbío', 8),
('Timbiquí', 8),
('Toribio', 8),
('Totoró', 8),
('Villa Rica', 8),
('Santander de Quilichao', 8),
('San Sebastián', 8),
('Páez', 8);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Neiva', 13),
('Acevedo', 13),
('Agrado', 13),
('Aipe', 13),
('Algeciras', 13),
('Altamira', 13),
('Baraya', 13),
('Campoalegre', 13),
('Colombia', 13),
('Elías', 13),
('Garzón', 13),
('Gigante', 13),
('Guadalupe', 13),
('Hobo', 13),
('Iquira', 13),
('Isnos', 13),
('La Argentina', 13),
('La Plata', 13),
('Nátaga', 13),
('Oporapa', 13),
('Paicol', 13),
('Palermo', 13),
('Palestina', 13),
('Pital', 13),
('Pitalito', 13),
('Rivera', 13),
('Saladoblanco', 13),
('Santa María', 13),
('Suaza', 13),
('Tarqui', 13),
('Tesalia', 13),
('Tello', 13),
('Teruel', 13),
('Timaná', 13),
('Villavieja', 13),
('Yaguará', 13),
('San Agustín', 13);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Achí', 4),
('Arenal', 4),
('Arjona', 4),
('Arroyohondo', 4),
('Calamar', 4),
('Cantagallo', 4),
('Cicuco', 4),
('Córdoba', 4),
('Clemencia', 4),
('El Guamo', 4),
('Magangué', 4),
('Mahates', 4),
('Margarita', 4),
('Montecristo', 4),
('Mompós', 4),
('Morales', 4),
('Norosí', 4),
('Pinillos', 4),
('Regidor', 4),
('Río Viejo', 4),
('San Estanislao', 4),
('San Fernando', 4),
('San Juan Nepomuceno', 4),
('Santa Catalina', 4),
('Santa Rosa', 4),
('Simití', 4),
('Soplaviento', 4),
('Talaigua Nuevo', 4),
('Tiquisio', 4),
('Turbaco', 4),
('Turbaná', 4),
('Villanueva', 4),
('Barranco de Loba', 4),
('Santa Rosa del Sur', 4),
('Hatillo de Loba', 4),
('El Carmen de Bolívar', 4),
('San Martín de Loba', 4),
('Altos del Rosario', 4),
('San Jacinto del Cauca', 4),
('San Pablo de Borbur', 4),
('San Jacinto', 4),
('El Peñón', 4),
('Cartagena', 4),
('María la Baja', 4),
('San Cristóbal', 4),
('Zambrano', 4);


INSERT INTO UsersDB.city (name, department_id)
VALUES
('Uribe', 16),
('Villavicencio', 16),
('Acacías', 16),
('Cabuyaro', 16),
('Cubarral', 16),
('Cumaral', 16),
('El Calvario', 16),
('El Castillo', 16),
('El Dorado', 16),
('Granada', 16),
('Guamal', 16),
('Mapiripán', 16),
('Mesetas', 16),
('La Macarena', 16),
('Lejanías', 16),
('Puerto Concordia', 16),
('Puerto Gaitán', 16),
('Puerto López', 16),
('Puerto Lleras', 16),
('Puerto Rico', 16),
('Restrepo', 16),
('San Juanito', 16),
('San Martín', 16),
('Vista Hermosa', 16),
('Barranca de Upía', 16),
('Fuente de Oro', 16),
('San Carlos de Guaroa', 16),
('San Juan de Arama', 16),
('Castilla la Nueva', 16);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Silos', 18),
('Cácota', 18),
('Toledo', 18),
('Mutiscua', 18),
('El Zulia', 18),
('Salazar', 18),
('Cucutilla', 18),
('Puerto Santander', 18),
('Gramalote', 18),
('El Tarra', 18),
('Teorama', 18),
('Arboledas', 18),
('Lourdes', 18),
('Bochalema', 18),
('Convención', 18),
('Hacarí', 18),
('Herrán', 18),
('Tibú', 18),
('San Cayetano', 18),
('San Calixto', 18),
('La Playa', 18),
('Chinácota', 18),
('Ragonvalia', 18),
('La Esperanza', 18),
('Villa del Rosario', 18),
('Chitagá', 18),
('Sardinata', 18),
('Abrego', 18),
('Los Patios', 18),
('Ocaña', 18),
('Bucarasica', 18),
('Santiago', 18),
('Labateca', 18),
('Cachirá', 18),
('Villa Caro', 18),
('Durania', 18),
('Pamplona', 18),
('Pamplonita', 18),
('Cúcuta', 18),
('El Carmen', 18);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Alpujarra', 23),
('Alvarado', 23),
('Ambalema', 23),
('Armero', 23),
('Ataco', 23),
('Cajamarca', 23),
('Chaparral', 23),
('Coello', 23),
('Coyaima', 23),
('Cunday', 23),
('Dolores', 23),
('Espinal', 23),
('Falan', 23),
('Flandes', 23),
('Fresno', 23),
('Guamo', 23),
('Herveo', 23),
('Honda', 23),
('Icononzo', 23),
('Mariquita', 23),
('Melgar', 23),
('Murillo', 23),
('Natagaima', 23),
('Ortega', 23),
('Palocabildo', 23),
('Piedras', 23),
('Planadas', 23),
('Prado', 23),
('Purificación', 23),
('Rio Blanco', 23),
('Roncesvalles', 23),
('Rovira', 23),
('Saldaña', 23),
('Santa Isabel', 23),
('Venadillo', 23),
('Villahermosa', 23),
('Villarrica', 23),
('Valle de San Juan', 23),
('Carmen de Apicala', 23),
('San Luis', 23),
('San Antonio', 23),
('Casabianca', 23),
('Anzoátegui', 23),
('Ibagué', 23),
('Líbano', 23),
('Lérida', 23),
('Suárez', 23);


INSERT INTO UsersDB.city (name, department_id)
VALUES
('El Dovio', 24),
('Roldanillo', 24),
('Argelia', 24),
('Sevilla', 24),
('Zarzal', 24),
('El Cerrito', 24),
('Cartago', 24),
('Caicedonia', 24),
('El Cairo', 24),
('La Unión', 24),
('Restrepo', 24),
('Dagua', 24),
('Guacarí', 24),
('Ansermanuevo', 24),
('Bugalagrande', 24),
('La Victoria', 24),
('Ginebra', 24),
('Yumbo', 24),
('Obando', 24),
('Bolívar', 24),
('Cali', 24),
('San Pedro', 24),
('Guadalajara de Buga', 24),
('Calima', 24),
('Andalucía', 24),
('Pradera', 24),
('Yotoco', 24),
('Palmira', 24),
('Riofrío', 24),
('Alcalá', 24),
('Versalles', 24),
('El Águila', 24),
('Toro', 24),
('Candelaria', 24),
('La Cumbre', 24),
('Ulloa', 24),
('Trujillo', 24),
('Vijes', 24),
('Tuluá', 24),
('Florida', 24),
('Jamundí', 24),
('Buenaventura', 24);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Pereira', 20),
('Apía', 20),
('Balboa', 20),
('Dosquebradas', 20),
('Guática', 20),
('La Celia', 20),
('La Virginia', 20),
('Marsella', 20),
('Mistrató', 20),
('Pueblo Rico', 20),
('Quinchía', 20),
('Santuario', 20),
('Santa Rosa de Cabal', 20),
('Belén de Umbría', 20);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Puerto Wilches', 21),
('Puerto Parra', 21),
('Bucaramanga', 21),
('Aguada', 21),
('Albania', 21),
('Aratoca', 21),
('Barbosa', 21),
('Barichara', 21),
('Barrancabermeja', 21),
('Betulia', 21),
('Bolívar', 21),
('Cabrera', 21),
('California', 21),
('Carcasí', 21),
('Cepitá', 21),
('Cerrito', 21),
('Charalá', 21),
('Charta', 21),
('Chipatá', 21),
('Cimitarra', 21),
('Concepción', 21),
('Confines', 21),
('Contratación', 21),
('Coromoro', 21),
('Curití', 21),
('El Guacamayo', 21),
('El Playón', 21),
('Encino', 21),
('Enciso', 21),
('Florián', 21),
('Floridablanca', 21),
('Galán', 21),
('Gambita', 21),
('Girón', 21),
('Guaca', 21),
('Guadalupe', 21),
('Guapotá', 21),
('Guavatá', 21),
('Güepsa', 21),
('Jesús María', 21),
('Jordán', 21),
('La Belleza', 21),
('Landázuri', 21),
('La Paz', 21),
('Lebríja', 21),
('Los Santos', 21),
('Macaravita', 21),
('Málaga', 21),
('Matanza', 21),
('Mogotes', 21),
('Molagavita', 21),
('Ocamonte', 21),
('Oiba', 21),
('Onzaga', 21),
('Palmar', 21),
('Páramo', 21),
('Piedecuesta', 21),
('Pinchote', 21),
('Puente Nacional', 21),
('Rionegro', 21),
('San Andrés', 21),
('San Gil', 21),
('San Joaquín', 21),
('San Miguel', 21),
('Santa Bárbara', 21),
('Simacota', 21),
('Socorro', 21),
('Suaita', 21),
('Sucre', 21),
('Suratá', 21),
('Tona', 21),
('Vélez', 21),
('Vetas', 21),
('Villanueva', 21),
('Zapatoca', 21),
('Palmas del Socorro', 21),
('San Vicente de Chucurí', 21),
('San José de Miranda', 21),
('Santa Helena del Opón', 21),
('Sabana de Torres', 21),
('El Carmen de Chucurí', 21),
('Valle de San José', 21),
('San Benito', 21),
('Hato', 21),
('Chimá', 21),
('Capitanejo', 21),
('El Peñón', 21);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Sincelejo', 22),
('Buenavista', 22),
('Caimito', 22),
('Coloso', 22),
('Coveñas', 22),
('Chalán', 22),
('El Roble', 22),
('Galeras', 22),
('Guaranda', 22),
('La Unión', 22),
('Los Palmitos', 22),
('Majagual', 22),
('Morroa', 22),
('Ovejas', 22),
('Palmito', 22),
('San Benito Abad', 22),
('San Marcos', 22),
('San Onofre', 22),
('San Pedro', 22),
('Sucre', 22),
('Tolú Viejo', 22),
('San Luis de Sincé', 22),
('San Juan de Betulia', 22),
('Santiago de Tolú', 22),
('Sampués', 22),
('Corozal', 22);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Barranquilla', 2),
('Baranoa', 2),
('Candelaria', 2),
('Galapa', 2),
('Luruaco', 2),
('Malambo', 2),
('Manatí', 2),
('Piojó', 2),
('Polonuevo', 2),
('Sabanagrande', 2),
('Sabanalarga', 2),
('Santa Lucía', 2),
('Santo Tomás', 2),
('Soledad', 2),
('Suan', 2),
('Tubará', 2),
('Usiacurí', 2),
('Juan de Acosta', 2),
('Palmar de Varela', 2),
('Campo de La Cruz', 2),
('Repelón', 2),
('Puerto Colombia', 2);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Valledupar', 9),
('Aguachica', 9),
('Agustín Codazzi', 9),
('Astrea', 9),
('Becerril', 9),
('Bosconia', 9),
('Chimichagua', 9),
('Chiriguaná', 9),
('Curumaní', 9),
('El Copey', 9),
('El Paso', 9),
('Gamarra', 9),
('González', 9),
('La Gloria', 9),
('Manaure', 9),
('Pailitas', 9),
('Pelaya', 9),
('Pueblo Bello', 9),
('La Paz', 9),
('San Alberto', 9),
('San Diego', 9),
('San Martín', 9),
('Tamalameque', 9),
('Río de Oro', 9),
('La Jagua de Ibirico', 9);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Pasto', 17),
('Albán', 17),
('Aldana', 17),
('Ancuyá', 17),
('Barbacoas', 17),
('Colón', 17),
('Consaca', 17),
('Contadero', 17),
('Córdoba', 17),
('Cuaspud', 17),
('Cumbal', 17),
('Cumbitara', 17),
('El Charco', 17),
('El Peñol', 17),
('El Rosario', 17),
('El Tambo', 17),
('Funes', 17),
('Guachucal', 17),
('Guaitarilla', 17),
('Gualmatán', 17),
('Iles', 17),
('Imués', 17),
('Ipiales', 17),
('La Cruz', 17),
('La Florida', 17),
('La Llanada', 17),
('La Tola', 17),
('La Unión', 17),
('Leiva', 17),
('Linares', 17),
('Los Andes', 17),
('Magüí', 17),
('Mallama', 17),
('Mosquera', 17),
('Nariño', 17),
('Olaya Herrera', 17),
('Ospina', 17),
('Francisco Pizarro', 17),
('Policarpa', 17),
('Potosí', 17),
('Providencia', 17),
('Puerres', 17),
('Pupiales', 17),
('Ricaurte', 17),
('Roberto Payán', 17),
('Samaniego', 17),
('Sandoná', 17),
('San Bernardo', 17),
('San Lorenzo', 17),
('San Pablo', 17),
('Santa Bárbara', 17),
('Sapuyes', 17),
('Taminango', 17),
('Tangua', 17),
('Túquerres', 17),
('Yacuanquer', 17),
('San Pedro de Cartago', 17),
('El Tablón de Gómez', 17),
('Buesaco', 17),
('San Andrés de Tumaco', 17),
('Belén', 17),
('Chachagüí', 17),
('Arboleda', 17);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Armenia', 19),
('Buenavista', 19),
('Circasia', 19),
('Córdoba', 19),
('Filandia', 19),
('La Tebaida', 19),
('Montenegro', 19),
('Pijao', 19),
('Quimbaya', 19),
('Salento', 19),
('Calarcá', 19),
('Génova', 19);

INSERT INTO UsersDB.city (name, department_id)
VALUES
('Mocoa', 27),
('Colón', 27),
('Orito', 27),
('Puerto Caicedo', 27),
('Puerto Guzmán', 27),
('Leguízamo', 27),
('Sibundoy', 27),
('San Francisco', 27),
('San Miguel', 27),
('Santiago', 27),
('Valle de Guamez', 27),
('Puerto Asís', 27),
('Villagarzón', 27);

INSERT INTO UsersDB.user (birth_date, document_number, document_type, email, name, phone_number, residence_address, university_code, user_type, city_id) VALUES 
("2001-09-12", "1002328321", "CC", "laura@uptc.edu.co", "LAURA DANIELA ROJAS SUAREZ", "3125678932", "Av Occidental", "202187652", "STUDENT", 6),
("2000-05-24", "1002456789", "CC", "carlos@uptc.edu.co", "CARLOS ANDRÉS PÉREZ LÓPEZ", "3156781234", "Cra 10 #12-34", "202198765", "STUDENT", 6),
("2002-03-18", "1002567890", "CC", "maria@uptc.edu.co", "MARÍA CAMILA RODRÍGUEZ PÉREZ", "3102345678", "Cl 23 #45-67", "202154321", "STUDENT", 6),
("1999-11-07", "1002678901", "CC", "andres@uptc.edu.co", "ANDRÉS FELIPE GÓMEZ MARTÍNEZ", "3134567890", "Av Norte #56-78", "202112345", "STUDENT", 6),
("2001-02-25", "1002789012", "CC", "luisa@uptc.edu.co", "LUISA FERNANDA TORRES RAMÍREZ", "3115678901", "Cl 78 #90-12", "202109876", "STUDENT", 6),
("2003-08-13", "1002890123", "CC", "diana@uptc.edu.co", "DIANA PATRICIA VARGAS SANTOS", "3178901234", "Av Sur #34-56", "202176543", "STUDENT", 6),
("1998-04-30", "1002901234", "CC", "jorge@uptc.edu.co", "JORGE ALEJANDRO CASTRO RIVERA", "3167890123", "Cra 7 #89-01", "202134567", "STUDENT", 6),
("2002-12-11", "1003012345", "CC", "camilo@uptc.edu.co", "CAMILO JOSÉ MONTOYA QUINTERO", "3145678901", "Cl 10 #11-22", "202198123", "STUDENT", 6),
("2000-07-19", "1003123456", "CC", "sofia@uptc.edu.co", "SOFÍA VALENTINA NIETO BERMÚDEZ", "3189012345", "Av Oriente #13-14", "202145678", "STUDENT", 6),
("1999-09-25", "1003234567", "CC", "diego@uptc.edu.co", "DIEGO ALFONSO MEJÍA PEÑA", "3190123456", "Cl 56 #78-90", "202132154", "STUDENT", 6),
("1999-09-25", "1003234567", "CC", "deportista@uptc.edu.co", "", "3190123456", "Cl 56 #78-90", "202132154", "ADMINISTRATIVE", 6),
("1999-09-25", "1003234567", "CC", "admin@uptc.edu.co", "", "3190123456", "Cl 56 #78-90", "202132154", "ADMINISTRATIVE", 6),
("1999-09-25", "1003234567", "CC", "coordinador@uptc.edu.co", "", "3190123456", "Cl 56 #78-90", "202132154", "ADMINISTRATIVE", 6),
("1999-09-25", "1003234567", "CC", "director@uptc.edu.co", "", "3190123456", "Cl 56 #78-90", "202132154", "ADMINISTRATIVE", 6);




